[en]
  title = "tandt53"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[vi]
  title = "tandt53"
  languageName = "Tiếng Việt"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/vi"
