[[main]]
  identifier = "about"
  name = "Giới thiệu"
  url = "about"
  weight = 1

[[main]]
  identifier = "java"
  name = "Java"
  url = "java"
  weight = 2

[[main]]
  identifier = "selenium"
  name = "Selenium"
  url = "selenium"
  weight = 3

[[main]]
  identifier = "appium"
  name = "Appium"
  url = "appium"
  weight = 4

[[main]]
  identifier = "automation-test"
  name = "Automation Test"
  url = "automation-test"
  weight = 5